name: CI

on:
  push:
    branches: ['main']

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout Code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: pnpm Setup
        uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
        with:
          version: 7.1.0
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@bea5baf987ba7aa777a8a0b4ace377a21c45c381 # v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
        id: deployInstall
      - name: Build
        run: pnpm run build
      - name: Setup Environment
        run: echo $TEST_ENV_FILE | base64 --decode > .env.test.local
        env:
          TEST_ENV_FILE: ${{ secrets.TEST_DOTENV }}
      - name: Run Unit Tests
        uses: paambaati/codeclimate-action@4cace242c6e0a2dd554bbb3cc12c58047d8af3e5 # v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: pnpm run test:unit:ci
      # - name: Run Integration Tests
      #   run: pnpm run test:integration:ci
