name: PR

on:
  - pull_request

jobs:
  continuous-integration:
    name:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: pnpm Setup
        uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
        with:
          version: 7.1.0
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
        id: deployInstall
      - name: Build
        run: pnpm run build
      - name: Setup Environment
        run: echo $TEST_ENV_FILE | base64 --decode > .env.test.local
        env:
          TEST_ENV_FILE: ${{ secrets.TEST_DOTENV }}
      - name: Run Unit Tests
        run: pnpm run test:unit:ci
